// <auto-generated />
namespace Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Balmeet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Balmeet));
        
        string IMigrationMetadata.Id
        {
            get { return "202002192303368_Balmeet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
